export const LOAD_CITIES = 'app/HomePage/LOAD_CITIES';
export const LOAD_CITIES_SUCCESS = 'app/HomePage/LOAD_CITIES_SUCCESS';
export const LOAD_CITIES_ERROR = 'app/HomePage/LOAD_CITIES_ERROR';

export const OPEN_FLIGHT_DIALOG = 'app/HomePage/OPEN_FLIGHT_DIALOG';
export const CLOSE_FLIGHT_DIALOG = 'app/HomePage/CLOSE_FLIGHT_DIALOG';

export const LOAD_DEPARTING_FLIGHT = 'app/HomePage/LOAD_DEPARTING_FLIGHT';
export const LOAD_DEPARTING_FLIGHT_SUCCESS =
  'app/HomePage/LOAD_DEPARTING_FLIGHT_SUCCESS';
export const LOAD_DEPARTING_FLIGHT_ERROR =
  'app/HomePage/LOAD_DEPARTING_FLIGHT_ERROR';

export const LOAD_ARRIVING_FLIGHT = 'app/HomePage/LOAD_ARRIVING_FLIGHT';
export const LOAD_ARRIVING_FLIGHT_SUCCESS =
  'app/HomePage/LOAD_ARRIVING_FLIGHT_SUCCESS';
export const LOAD_ARRIVING_FLIGHT_ERROR =
  'app/HomePage/LOAD_ARRIVING_FLIGHT_ERROR';
